services:
  ignite-call-next-14: 
    container_name: ignite-call-next-14
    image: bitnami/postgresql
    ports:
     - 5432:5432
    environment:
      POSTGRESQL_USERNAME: ${DATABASE_USERNAME}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${DATABASE_NAME}